### ISSUE TITLE
TypeError: fetch failed

### ISSUE THREAD

**Issue by ExCrino** [CikeyQi/nsfwjs-plugin#11]
![image](https://github.com/CikeyQi/nsfwjs-plugin/assets/39008950/8db67c47-9cfb-4996-a40f-1f7078a35c7d)

如图所示，是这样的错误

**Comment by ElaineOwO** [comment]
一样，我接的是NTQQ  不知道是不是ws接口的问题

**Comment by daqyt** [comment]
请问这个问题解决了吗？我现在也有这个问题

**Comment by CikeyQi** [comment]
已解决该问题
