### ISSUE TITLE
启动时报错，好像是CPU不支持什么东西

### ISSUE THREAD

**Issue by ElaineOwO** [CikeyQi/nsfwjs-plugin#15]
0|Miao-Yunzai  |I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
0|Miao-Yunzai  | To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

电脑的CPU是i5-6500

**Comment by CikeyQi** [comment]
这不是一个报错信息，而是一段关于TensorFlow二进制文件优化的说明。它表明该TensorFlow二进制文件被优化为使用AVX2指令集进行性能关键操作，并建议在其他操作中重新构建TensorFlow并使用相应的编译器标志以启用这些指令。

简单来说，它是一种优化措施，旨在提高TensorFlow在使用AVX2指令集的CPU上的性能。所以你可以无视他。
