### ISSUE TITLE
[BUG]测试时检测涩图导致BOT重启

### ISSUE THREAD

**Issue by jiucheng008** [CikeyQi/nsfwjs-plugin#20]
###  日志
**日志如下：**未发现明显报错
0|Miao-Yunzai| [MiaoYz][02:22:20.745][INFO] recv from: [Group: 风神忽悠群(851648300), Member: 邪(2749128036)] {image:17EDA258946A146872518FA0DC6853F8}
0|Miao-Yunzai  | [MiaoYz][02:22:21.960][INFO] succeed to send: [Group(851648300)] [图片]
0|Miao-Yunzai  | [MiaoYz][02:22:22.680][INFO] recv from: [Group: 风神忽悠群(851648300), Member: 城.(接代)(3483156709)] 6
0|Miao-Yunzai  | [MiaoYz][02:22:29.458][WARN] 【NSFWJS-Plugin v0.0.2】 【NSFWJS】检测到变态图像
0|Miao-Yunzai  | [
0|Miao-Yunzai  |   '啾咪啊！这里有人涩涩啊！',
0|Miao-Yunzai  |   {
0|Miao-Yunzai  |     type: 'image',
0|Miao-Yunzai  |     file: 'https://c2cpicdw.qpic.cn/offpic_new/3146312184//3146312184-3207407400-FA958C114CE3368AF4DFAF469172761C/0?term=2&is_origin=0',
0|Miao-Yunzai  |     cache: undefined,
0|Miao-Yunzai  |     timeout: undefined,
0|Miao-Yunzai  |     headers: undefined
0|Miao-Yunzai  |   },
0|Miao-Yunzai  |   '快来人管一管啊！'
0|Miao-Yunzai  | ]
0|Miao-Yunzai  | [MiaoYz][02:22:30.379][INFO] succeed to send: [Private(3483156709)] [NSFWJS]涩图监听
0|Miao-Yunzai  | 来自群聊：风神忽悠群(851648300)
0|Miao-Yunzai  | 发送用户：邪(2749128036)
0|Miao-Yunzai  | 违规类型：Hentai(97.89%)
0|Miao-Yunzai  | [图片]
0|Miao-Yunzai  | [MiaoYz][02:22:31.007][INFO] succeed to send: [Group(851648300)] [回复@邪]啾咪啊！这里有人涩涩啊！[图片]快来人管一管啊！
0|Miao-Yunzai  | [MiaoYz][02:22:31.994][INFO] recv from: [Group: 风神忽悠群(851648300), Member: 邪(2749128036)] {image:17EDA258946A146872518FA0DC6853F8}
0|Miao-Yunzai  | [MiaoYz][02:22:33.056][INFO] recv from: [Group: 风神忽悠群(851648300), Member: 缘(3302150733)] 我好像看见了，不该看的
0|Miao-Yunzai  | [MiaoYz][02:22:35.739][INFO] recv from: [Group: 风神忽悠群(851648300), Member: 城.(接代)(3483156709)] {at:2105200875} 撤回
0|Miao-Yunzai  | [MiaoYz][02:22:37.040][MARK] [椰奶小助手][RecallMsgown][风神忽悠群(城.(接代))] 撤回
0|Miao-Yunzai  | [MiaoYz][02:22:39.719][MARK] Miao-Yunzai 启动中...
0|Miao-Yunzai  | [MiaoYz][02:22:39.731][INFO] 正在连接 redis://127.0.0.1:6379/0
0|Miao-Yunzai  | [MiaoYz][02:22:39.781][INFO] Redis 连接成功
0|Miao-Yunzai  | [MiaoYz][02:22:39.853][MARK] ----------
0|Miao-Yunzai  | [MiaoYz][02:22:39.862][MARK] Package Version: icqq@0.6.5 (Released on 2023/11/30)
0|Miao-Yunzai  | [MiaoYz][02:22:39.863][MARK] View Changelogs：https://github.com/icqqjs/icqq/releases
0|Miao-Yunzai  | [MiaoYz][02:22:39.863][MARK] ----------
0|Miao-Yunzai  | [MiaoYz][02:22:41.533][INFO] [Chromium] /snap/bin/chromium
0|Miao-Yunzai  | [MiaoYz][02:22:41.535][INFO] 加载渲染后端 puppeteer
0|Miao-Yunzai  | [MiaoYz][02:22:41.986][INFO] [2105200875]使用协议：aPad_8.9.90.13250
0|Miao-Yunzai  | [MiaoYz][02:22:43.377][MARK] 121.229.94.199:8080 connected
0|Miao-Yunzai  | [MiaoYz][02:22:43.594][MARK] Welcome, 可可 ! 正在加载资源...
0|Miao-Yunzai  | [MiaoYz][02:22:48.610][MARK] 加载了13个好友，4个群，0个频道，0个陌生人
0|Miao-Yunzai  | [MiaoYz][02:22:48.615][MARK] ----^_^----
0|Miao-Yunzai  | [MiaoYz][02:22:48.617][MARK] Miao-Yunzai 上线成功 版本v3.1.3
0|Miao-Yunzai  | [MiaoYz][02:22:48.618][MARK] https://github.com/yoimiya-kokomi/Miao-Yunzai
0|Miao-Yunzai  | [MiaoYz][02:22:48.642][INFO] 加载插件中..
0|Miao-Yunzai  | [MiaoYz][02:22:48.673][INFO] ---------QAQ---------
0|Miao-Yunzai  | [MiaoYz][02:22:48.675][INFO] Atlas图鉴4.3.0很高兴为您服务~
0|Miao-Yunzai  | [MiaoYz][02:22:49.643][INFO] Atlas载入库文件：github原神成功！
0|Miao-Yunzai  | [MiaoYz][02:22:49.666][INFO] Atlas载入库文件：github星铁成功！
0|Miao-Yunzai  | [MiaoYz][02:22:49.668][INFO] Atlas载入库文件：github绝区零成功！
0|Miao-Yunzai  | [MiaoYz][02:22:49.719][INFO] Atlas载入库文件：原神成功！
0|Miao-Yunzai  | [MiaoYz][02:22:49.725][INFO] Atlas载入库文件：星铁成功！
0|Miao-Yunzai  | [MiaoYz][02:22:49.726][INFO] Atlas载入库文件：绝区零成功！
0|Miao-Yunzai  | [MiaoYz][02:22:49.735][INFO] Eggy抽奖模拟启动中....
0|Miao-Yunzai  | [MiaoYz][02:22:49.770][MARK] Eggy抽奖模拟启动成功！
0|Miao-Yunzai  | [MiaoYz][02:22:50.155][INFO] recv from: [Group: 风神忽悠群(851648300), Member: 城.(接代)(3483156709)] 又崩重启了
0|Miao-Yunzai  | [MiaoYz][02:22:50.739][MARK] --------- >_< ---------
0|Miao-Yunzai  | [MiaoYz][02:22:50.739][MARK] 锅巴服务启动成功~ 耗时:201ms
0|Miao-Yunzai  | [MiaoYz][02:22:50.740][MARK] http://8.140.254.159:10022
0|Miao-Yunzai  | [MiaoYz][02:22:50.746][MARK] -----------------------
0|Miao-Yunzai  | [MiaoYz][02:22:50.746][MARK] [Guoba] 欢迎使用锅巴插件，当前版本：1.2.1
0|Miao-Yunzai  | [MiaoYz][02:22:50.769][INFO] Σ(°Д°;--Σ(°Д°;--Σ(°Д°;--Σ(°Д°;--Σ(°Д°;
0|Miao-Yunzai  | [MiaoYz][02:22:50.769][INFO]             脆脆鲨插件载入成功            
0|Miao-Yunzai  | [MiaoYz][02:22:50.771][INFO]    有关本插件问题请加群657142904咨询       
0|Miao-Yunzai  | [MiaoYz][02:22:50.771][INFO]             非常感谢您的使用!!!           
0|Miao-Yunzai  | [MiaoYz][02:22:50.772][INFO] ---------------------------------------
0|Miao-Yunzai  | [MiaoYz][02:22:50.943][INFO] [XiaoXuePlugin]~~~~~~~~~~~~~~~~~~~~ QAQ ~~~~~~~~~~~~~~~~~~~~~
0|Miao-Yunzai  | [MiaoYz][02:22:50.958][INFO] [XiaoXuePlugin]~          欢迎使用小雪插件                ~
0|Miao-Yunzai  | [MiaoYz][02:22:50.958][INFO] [XiaoXuePlugin]~  版本    3.4.1                           ~
0|Miao-Yunzai  | [MiaoYz][02:22:50.961][INFO] [XiaoXuePlugin]~  作者    雪儿不怕冷                      ~
0|Miao-Yunzai  | [MiaoYz][02:22:50.961][INFO] [XiaoXuePlugin]~  交流群  893576718                       ~
0|Miao-Yunzai  | [MiaoYz][02:22:50.962][INFO] [XiaoXuePlugin]~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0|Miao-Yunzai  | [MiaoYz][02:22:52.262][INFO] recv from: [Group: 风神忽悠群(851648300), Member: 城.(接代)(3483156709)] 啊？
0|Miao-Yunzai  | [MiaoYz][02:22:53.375][INFO] akasha-terminal-plugin[2023-1-19]
0|Miao-Yunzai  | [MiaoYz][02:22:53.453][INFO] Template detection:存在非class属性default导出
0|Miao-Yunzai  |     ../../apps/help/theme.js
0|Miao-Yunzai  | [MiaoYz][02:22:53.639][INFO] 🌱🌱🌱🌱🌱🌱🌱🌱
0|Miao-Yunzai  | [MiaoYz][02:22:53.640][INFO] (🍀Akasha-Terminal-Plugin🍀):"虚空插件"初始化.....
0|Miao-Yunzai  | [MiaoYz][02:22:53.641][INFO] ┎┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┒
0|Miao-Yunzai  | [MiaoYz][02:22:53.641][INFO] ┃      ⋏    ┅┅┅┅┳┅┅┅┅  ┎┅┅┅┅┅┅┒ ┃
0|Miao-Yunzai  | [MiaoYz][02:22:53.641][INFO] ┃     / \       ┋      ┃      ┃ ┃
0|Miao-Yunzai  | [MiaoYz][02:22:53.642][INFO] ┃    /───\      ┋      ┠┅┅┅┅┅┅┚ ┃
0|Miao-Yunzai  | [MiaoYz][02:22:53.642][INFO] ┃   /     \     ┋      ┃        ┃
0|Miao-Yunzai  | [MiaoYz][02:22:53.643][INFO] ┃  /       \    ┋      ┃        ┃
0|Miao-Yunzai  | [MiaoYz][02:22:53.643][INFO] ┖┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┚
0|Miao-Yunzai  | [MiaoYz][02:22:53.644][WARN] (🍀Akasha-Terminal-Plugin🍀):若出现README.md中未提及的问题,请联系我们!!!
0|Miao-Yunzai  | [MiaoYz][02:22:53.644][INFO] (🍀Akasha-Terminal-Plugin🍀):"初始化完成,祝您游玩愉快!🌴
0|Miao-Yunzai  | [MiaoYz][02:22:53.647][INFO] 🌴🌴🌴🌴🌴🌴🌴🌴
0|Miao-Yunzai  | [MiaoYz][02:22:53.667][INFO] ---------!_!---------
0|Miao-Yunzai  | [MiaoYz][02:22:53.667][INFO] 自动化插件1.0.5载入成功
0|Miao-Yunzai  | [MiaoYz][02:22:53.886][INFO] ---------=.=---------
0|Miao-Yunzai  | [MiaoYz][02:22:53.887][INFO] 土块插件2.0.1载入成功~qwq
0|Miao-Yunzai  | [MiaoYz][02:22:53.887][INFO] 作者-SunRyK曉K & 地球生物
0|Miao-Yunzai  | [MiaoYz][02:22:53.887][INFO] ---------------------
0|Miao-Yunzai  | [MiaoYz][02:22:54.557][INFO] --------- >_< ---------
0|Miao-Yunzai  | [MiaoYz][02:22:54.557][INFO] 抽卡插件2.34.3很高兴为您服务~
0|Miao-Yunzai  | [MiaoYz][02:22:55.066][INFO] - 正在载入 GPTI-PLUGIN
0|Miao-Yunzai  | load Uid Data Done...
0|Miao-Yunzai  | [MiaoYz][02:22:55.126][INFO] - GPTI-PLUGIN 载入成功
0|Miao-Yunzai  | [MiaoYz][02:22:55.127][INFO] - 欢迎加入新组织【貓娘樂園🍥🏳️‍⚧️】（群号 551081559）
0|Miao-Yunzai  | [MiaoYz][02:22:55.243][INFO] recv from: [Group: 风神忽悠群(851648300), Member: 邪(2749128036)] {at:3302150733} {at:3302150733}  不，你没看见
0|Miao-Yunzai  | [MiaoYz][02:22:56.448][INFO] ********************[hanhan]********************
0|Miao-Yunzai  | [MiaoYz][02:22:56.449][INFO] hanhan-plugin加载成功
0|Miao-Yunzai  | [MiaoYz][02:22:56.449][INFO]             ▃▆█▇▄▖
0|Miao-Yunzai  | [MiaoYz][02:22:56.449][INFO] 　 　 　 ▟◤▖      ◥█▎
0|Miao-Yunzai  | [MiaoYz][02:22:56.449][INFO]    　 ◢◤　 ▐　　　  ▐▉
0|Miao-Yunzai  | [MiaoYz][02:22:56.449][INFO] 　 ▗◤　　　▂　▗▖　　▕█▎
0|Miao-Yunzai  | [MiaoYz][02:22:56.449][INFO] 　◤　▗▅▖◥▄　▀◣　　█▊
0|Miao-Yunzai  | [MiaoYz][02:22:56.450][INFO] ▐　▕▎◥▖◣◤　　　　◢██
0|Miao-Yunzai  | [MiaoYz][02:22:56.450][INFO] █◣　◥▅█▀　　　　▐██◤
0|Miao-Yunzai  | [MiaoYz][02:22:56.450][INFO] ▐█▙▂　　     　◢██◤
0|Miao-Yunzai  | [MiaoYz][02:22:56.450][INFO] ◥██◣　　　　◢▄◤
0|Miao-Yunzai  | [MiaoYz][02:22:56.450][INFO]  　　▀██▅▇▀
0|Miao-Yunzai  | [MiaoYz][02:22:56.450][INFO] 当前版本 v1.5.7
0|Miao-Yunzai  | [MiaoYz][02:22:56.450][INFO] 插件群：461601720
0|Miao-Yunzai  | [MiaoYz][02:22:56.451][INFO] 仓库地址 https://github.com/hanhan258/hanhan-plugin
0|Miao-Yunzai  | [MiaoYz][02:22:56.451][INFO] ********************[///^///]********************
0|Miao-Yunzai  | [MiaoYz][02:22:56.472][INFO] ~~~~~~~~~~~~~~~~~~~~
0|Miao-Yunzai  | [MiaoYz][02:22:56.472][INFO] 开始寸幼萱淫趴初始化
0|Miao-Yunzai  | [MiaoYz][02:22:56.474][INFO] 配置文件MyProfile.yaml已经存在，略过初始化~
0|Miao-Yunzai  | [MiaoYz][02:22:56.475][INFO] 配置文件bind.yaml已经存在，略过初始化~
0|Miao-Yunzai  | [MiaoYz][02:22:56.475][INFO] 配置文件config.js已经存在，略过初始化~
0|Miao-Yunzai  | [MiaoYz][02:22:56.475][INFO] 配置文件daoguanzi.yaml已经存在，略过初始化~
0|Miao-Yunzai  | [MiaoYz][02:22:56.475][INFO] 配置文件data.yaml已经存在，略过初始化~
0|Miao-Yunzai  | [MiaoYz][02:22:56.476][INFO] 配置文件system.yaml已经存在，略过初始化~
0|Miao-Yunzai  | [MiaoYz][02:22:56.559][MARK] [寸幼萱淫趴][model/GetYamlValue]开始调用获取控制面板值函数...
0|Miao-Yunzai  | [MiaoYz][02:22:56.559][MARK] 目标文件名：daoguanzi.yaml
0|Miao-Yunzai  | [MiaoYz][02:22:56.570][MARK] 正在读取群单独配置....
0|Miao-Yunzai  | [MiaoYz][02:22:56.571][MARK] 群单独配置获取失败，正在读取默认配置...
0|Miao-Yunzai  | [MiaoYz][02:22:56.571][MARK] 群单独配置读取失败，正在直接读取....
0|Miao-Yunzai  | [MiaoYz][02:22:56.572][INFO] 直接读取成功，返回：导管子|打胶
0|Miao-Yunzai  | [MiaoYz][02:22:56.573][MARK] [寸幼萱淫趴][model/GetYamlValue]开始调用获取控制面板值函数...
0|Miao-Yunzai  | [MiaoYz][02:22:56.573][MARK] 目标文件名：MyProfile.yaml
0|Miao-Yunzai  | [MiaoYz][02:22:56.575][MARK] 正在读取群单独配置....
0|Miao-Yunzai  | [MiaoYz][02:22:56.575][MARK] 群单独配置获取失败，正在读取默认配置...
0|Miao-Yunzai  | [MiaoYz][02:22:56.575][MARK] 群单独配置读取失败，正在直接读取....
0|Miao-Yunzai  | [MiaoYz][02:22:56.576][INFO] 直接读取成功，返回：(淫|银|阴)(趴|扒|啪|爬)(信息|面板)
0|Miao-Yunzai  | [MiaoYz][02:22:56.585][INFO] 寸幼萱插淫趴件初始化完成
0|Miao-Yunzai  | [MiaoYz][02:22:56.586][INFO] ~ 寸幼萱交流群  786034611 ~
0|Miao-Yunzai  | [MiaoYz][02:22:56.587][INFO] ~~~~~~~~~~~~~~~~~~~~
0|Miao-Yunzai  | [MiaoYz][02:22:56.820][INFO] ~~~~~~~~~~~ ^_^ ~~~~~~~~~~~
0|Miao-Yunzai  | [MiaoYz][02:22:56.822][INFO] ~ 欢迎使用榴莲插件
0|Miao-Yunzai  | [MiaoYz][02:22:56.822][INFO] ~ 版本：  0.5.7
0|Miao-Yunzai  | [MiaoYz][02:22:56.822][INFO] ~ 作者：会飞的芒果猫&萧枘
0|Miao-Yunzai  | [MiaoYz][02:22:56.822][INFO] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0|Miao-Yunzai  |        榴莲插件0.5.7初始化~
0|Miao-Yunzai  | [MiaoYz][02:22:56.939][INFO] ---------^_^---------
0|Miao-Yunzai  | [MiaoYz][02:22:56.939][INFO] 喵喵插件2.5.6初始化~
0|Miao-Yunzai  | [MiaoYz][02:22:56.950][INFO] - 正在载入 NSFWJS-PLUGIN
0|Miao-Yunzai  | 2024-01-18 02:22:58.327373: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
0|Miao-Yunzai  | To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
0|Miao-Yunzai  | [MiaoYz][02:22:58.338][INFO] - NSFWJS-PLUGIN 载入成功
0|Miao-Yunzai  | [MiaoYz][02:22:58.339][INFO] - 欢迎加入新组织【貓娘樂園🍥🏳️‍⚧️】（群号 551081559）
0|Miao-Yunzai  | [MiaoYz][02:22:58.553][INFO] 卿何插件初始化

**Comment by CikeyQi** [comment]
应该是内存爆了？尝试给pm2更大的内存，修改config/pm2/pm2.json中的max_memory_restart可能有用
