### ISSUE TITLE
安装依赖时出现 ELIFECYCLE  Command failed with exit code 1.报错，并根据issues的内容尝试更改无果

### ISSUE THREAD

**Issue by jym2009** [CikeyQi/nsfwjs-plugin#28]
C:\Users\Administrator\Desktop\Miao-Yunzai>pnpm i
Scope: all 9 workspace projects
plugins/miao-plugin                      |  WARN  deprecated request@2.88.2
 WARN  deprecated icqq@0.6.10: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
 WARN  4 deprecated subdependencies found: @npmcli/move-file@1.1.2, har-validator@5.1.5, phin@2.9.3, uuid@3.4.0
Packages: +57
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 836, reused 835, downloaded 0, added 0, done
node_modules/.pnpm/@tensorflow+tfjs-node@3.21.1_encoding@0.1.13_seedrandom@3.0.5/node_modules/@tensorflow/tfjs-node: Runnode_modules/.pnpm/@tensorflow+tfjs-node@3.21.1_encoding@0.1.13_seedrandom@3.0.5/node_modules/@tensorflow/tfjs-node: Running install script, failed in 1s
.../node_modules/@tensorflow/tfjs-node install$ node scripts/install.js
│ CPU-windows-3.21.1.zip
│ * Downloading libtensorflow
│ https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-2.9.1.zip
│ node:events:496
│       throw er; // Unhandled 'error' event
│       ^
│ Error: read ECONNRESET
│     at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
│ Emitted 'error' event on ClientRequest instance at:
│     at TLSSocket.socketErrorListener (node:_http_client:500:9)
│     at TLSSocket.emit (node:events:518:28)
│     at emitErrorNT (node:internal/streams/destroy:169:8)
│     at emitErrorCloseNT (node:internal/streams/destroy:128:3)
│     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
│   errno: -4077,
│   code: 'ECONNRESET',
│   syscall: 'read'
│ }
│ Node.js v20.12.0
└─ Failed in 1s at C:\Users\Administrator\Desktop\Miao-Yunzai\node_modules\.pnpm\@tensorflow+tfjs-node@3.21.1_encoding@0.1.13_seedrandom@3.0.5\node_modules\@tensorflow\tfjs-node
 ELIFECYCLE  Command failed with exit code 1.
![F55165A2FB025EC7E8FE344DEAA62388](https://github.com/CikeyQi/nsfwjs-plugin/assets/152615428/d32bd2bc-4857-4529-a4f0-dd8a7d8e99b5)
![屏幕截图 2024-05-18 004800](https://github.com/CikeyQi/nsfwjs-plugin/assets/152615428/2a8a7993-14a2-426d-8f29-3bfde6c241e1)

**Comment by CikeyQi** [comment]
`read ECONNRESET` 看样子是网络问题

**Comment by CikeyQi** [comment]
感觉是 `https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-2.9.1.zip` 没能下载成功，建议挂梯子重试
