### ISSUE TITLE
安装依赖时报错

### ISSUE THREAD

**Issue by 34200501** [CikeyQi/nsfwjs-plugin#29]
pnpm install --filter=nsfwjs-plugin
.                                        |  WARN  deprecated icqq@0.6.10
plugins/miao-plugin                      |  WARN  deprecated request@2.88.2
 WARN  12 deprecated subdependencies found: @npmcli/move-file@1.1.2, are-we-there-yet@2.0.0, gauge@3.0.2, glob@7.2.3, har-validator@5.1.5, inflight@1.0.6, npmlog@5.0.1, npmlog@6.0.2, phin@2.9.3, rimraf@2.7.1, rimraf@3.0.2, uuid@3.4.0
.                                        |  +59 ++++++
Progress: resolved 864, reused 845, downloaded 0, added 0, done
node_modules/.pnpm/@tensorflow+tfjs-node@3.21.1_encoding@0.1.13_seedrandom@3.0.5/node_modules/@tensorflow/tfjs-node: Runnode_modules/.pnpm/@tensorflow+tfjs-node@3.21.1_encoding@0.1.13_seedrandom@3.0.5/node_modules/@tensorflow/tfjs-node: Running install script, failed in 594ms
.../node_modules/@tensorflow/tfjs-node install$ node scripts/install.js
│ CPU-windows-3.21.1.zip
│ * Building TensorFlow Node.js bindings
│ symlink ./lib/napi-v9 failed:  Error: Command failed: node scripts/deps-stage.js symlink ./lib/napi-v9
│   * Symlink of lib\napi-v9\tensorflow.dll failed, creating a copy on disk.
│ node:internal/process/promises:289
│             triggerUncaughtException(err, true /* fromPromise */);
│             ^
│ [Error: ENOENT: no such file or directory, copyfile 'D:\Server\Bot\Yunzai\Yunzai-Bot\node_modules\.pnpm\@tensorflow…
│   errno: -4058,
│   code: 'ENOENT',
│   syscall: 'copyfile',
│   path: 'D:\\Server\\Bot\\Yunzai\\Yunzai-Bot\\node_modules\\.pnpm\\@tensorflow+tfjs-node@3.21.1_encoding@0.1.13_see…
│   dest: 'D:\\Server\\Bot\\Yunzai\\Yunzai-Bot\\node_modules\\.pnpm\\@tensorflow+tfjs-node@3.21.1_encoding@0.1.13_see…
│ }
│ Node.js v20.11.1
│     at ChildProcess.exithandler (node:child_process:422:12)
│     at ChildProcess.emit (node:events:518:28)
│     at maybeClose (node:internal/child_process:1105:16)
│     at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
│   code: 1,
│   killed: false,
│   signal: null,
│   cmd: 'node scripts/deps-stage.js symlink ./lib/napi-v9'
│ }
└─ Failed in 594ms at D:\Server\Bot\Yunzai\Yunzai-Bot\node_modules\.pnpm\@tensorflow+tfjs-node@3.21.1_encoding@0.1.13_seedrandom@3.0.5\node_modules\@tensorflow\tfjs-node
 ELIFECYCLE  Command failed with exit code 1.

**Comment by ycxom** [comment]
插件目录下，复制多一份napi-v8命名为napi-v9，（我是使用miao-yunzai，win server 2025的，目前可以安装）

**Comment by 34200501** [comment]
> 插件目录下，复制多一份napi-v8命名为napi-v9，（我是使用miao-yunzai，win server 2025的，目前可以安装）

成了！感谢义父！
