### ISSUE TITLE
非法指令（核心已转储）

### ISSUE THREAD

**Issue by ikenxuan** [CikeyQi/nsfwjs-plugin#3]
如图，安装插件后就载入报错并终止了node进程，不知道为什么，望大佬修复
![QQ截图20230805032858](https://github.com/CikeyQi/nsfwjs-plugin/assets/112480306/b467de87-5080-4c10-93bb-bf7f55ff69ab)
Ubuntu 22lts，node18lts

**Comment by CikeyQi** [comment]
上网查了下，可能是CPU过旧导致无法进行推理。除此之外，还有很多种可能，我这边不好排查，希望您能进一步反馈，感谢
