### ISSUE TITLE
Error: The Node.js native addon module (tfjs_bindin g.node) can not be found at path

### ISSUE THREAD

**Issue by tym2008** [CikeyQi/nsfwjs-plugin#5]
![image](https://github.com/CikeyQi/nsfwjs-plugin/assets/102407847/0a7b8553-73ea-4180-a604-3866943c8f10)
TRSS崽，CPU I5-11260H,4G内存（虚拟机

**Comment by CikeyQi** [comment]
[issues](https://github.com/CikeyQi/nsfwjs-plugin/issues/6#issuecomment-1685176794)
