### ISSUE TITLE
Error: The specified module could not be found.

### ISSUE THREAD

**Issue by 54Longwu** [CikeyQi/nsfwjs-plugin#6]
插件加载不出来，但全部更新到最新版本
![报错](https://github.com/CikeyQi/nsfwjs-plugin/assets/127602226/9878d5c8-f25b-400e-b9ac-af62b3a6ba7a)

**Comment by tym2008** [comment]
去看这里面：
node_modules\.pnpm\@tensorflow+tfjs-node@3.18.0_seedrandom@2.4.4\node_modules\@tensorflow\tfjs-node\lib
让两个文件夹（我是v8和v9，用的nodejsv20.5.1，windows server 2019），让里面都有tensorflow.dll和tfjs_binding.node，之后再试试
但是我第一次pnpm install的时候会提示无法创建链接啥的，要手动创建napi-v9这个文件夹才能正常pnpm install

**Comment by CikeyQi** [comment]
请下载 [文件地址](https://github.com/CikeyQi/nsfwjs-plugin/releases/tag/%E7%BC%BA%E5%A4%B1%E7%9A%84%E6%96%87%E4%BB%B6) 下的 `tensorflow.dll` 和 `tfjs_binding.node` 这两个文件放置在云崽根目录下的 `Yunzai\node_modules\.pnpm\@tensorflow+tfjs-node@3.21.1_seedrandom@3.0.5\node_modules\@tensorflow\tfjs-node\lib\napi-v8` 文件夹内，并在上一级的 `lib` 文件夹中新建 `napi-v9` 目录，再次运行 `pnpm install --filter=nsfwjs-plugin` 确认无报错即可解决。

参考文献：[#4116](https://github.com/tensorflow/tfjs/issues/4116)

更多问题可在TensorFlow官方issues内搜索关键错误信息：[issues](https://github.com/tensorflow/tfjs/issues)

**Comment by 54Longwu** [comment]
![image](https://github.com/CikeyQi/nsfwjs-plugin/assets/127602226/7260ad18-37a6-4776-ab02-9df1addd7cd1)
苏打姐姐照你方法做了还是报错

**Comment by tym2008** [comment]
试试崽根目录的node_modules\.pnpm\@tensorflow+tfjs-node@3.18.0_seedrandom@2.4.4\node_modules\@tensorflow\tfjs-node\lib，之后在根目录pnpm i应该能解决（亲测winserver2019+trss崽正常）

**Comment by Conkinya** [comment]
> tfjs_binding.node

全局都没tfjs_binding.node，已经搜索整个yunzai目录

**Comment by tym2008** [comment]
> > tfjs_binding.node
> 
> 全局都没tfjs_binding.node，已经搜索整个yunzai目录

pnpm i了吗？node_modules/.pnpm/里面有tensorflow+tfjs-node的文件吗？再确认下
